const featureProduct = [
  {
    id: 1,
    name: "Fork",
    description: " this is Fork",
    src: "https://preview.colorlib.com/theme/ogani/img/featured/feature-1.jpg.webp",
    price: 15000,
    discount: 0,
    weight: 0.4,
  },
  {
    id: 2,
    name: "Banana",
    description: " this is Banana",
    src: "https://preview.colorlib.com/theme/ogani/img/featured/feature-2.jpg.webp",
    price: 15000,
    discount: 0,
    weight: 0.4,
  },
  {
    id: 3,
    name: "Guava",
    description: " this is Guava",
    src: "https://preview.colorlib.com/theme/ogani/img/featured/feature-3.jpg.webp",
    price: 15000,
    discount: 0,
    weight: 0.4,
  },
  {
    id: 4,
    name: "Watermelon",
    description: " this is Watermelon",
    src: "https://preview.colorlib.com/theme/ogani/img/featured/feature-4.jpg.webp",
    price: 15000,
    discount: 0,
    weight: 0.4,
  },
  {
    id: 5,
    name: "Grape",
    description: " this is Grape",
    src: "https://preview.colorlib.com/theme/ogani/img/featured/feature-5.jpg.webp",
    price: 15000,
    discount: 0,
    weight: 0.4,
  },
  {
    id: 6,
    name: "Hambuger",
    description: " this is Hambuger",
    src: "https://preview.colorlib.com/theme/ogani/img/featured/feature-6.jpg.webp",
    price: 15000,
    discount: 0,
    weight: 0.4,
  },
  {
    id: 7,
    name: "Mango",
    description: " this is Mango",
    src: "https://preview.colorlib.com/theme/ogani/img/featured/feature-7.jpg.webp",
    price: 15000,
    discount: 0,
    weight: 0.4,
  },
  {
    id: 8,
    name: "Apple",
    description: " this is Apple",
    src: "https://preview.colorlib.com/theme/ogani/img/featured/feature-8.jpg.webp",
    price: 15000,
    discount: 0,
    weight: 0.4,
  },
];
export default featureProduct;
